/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_clear_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly().optional(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_clear_result$schema = z.object({
  'deleted': z.number().readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_delete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_delete_result$schema = z.object({
  'deleted': z.boolean().readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_parameter_1$schema = z.object({
  'prompt': z.string().readonly(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_result$schema = z.object({
  'record': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly(),
  'originalPrompt': z.string().readonly(),
  'enhancedPrompt': z.string().readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly(),
  'trace': z.array(z.object({
  'kind': z.union([z.literal("context"), z.literal("model")]).readonly(),
  'label': z.string().readonly(),
  'reference': z.string().readonly().optional(),
  'summary': z.string().readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
}).readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_list_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly().optional(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_list_result$schema = z.object({
  'records': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly(),
  'originalPrompt': z.string().readonly(),
  'enhancedPrompt': z.string().readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly(),
  'trace': z.array(z.object({
  'kind': z.union([z.literal("context"), z.literal("model")]).readonly(),
  'label': z.string().readonly(),
  'reference': z.string().readonly().optional(),
  'summary': z.string().readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
})

export const TYPERT_REMOTE = {
  package: 'dsh-prompt-enhancement',
  descriptors: [
    {
      id: 'dsh-prompt-enhancement#promptEnhancement/clear',
      service: 'promptEnhancement',
      namespace: 'promptEnhancement',
      method: 'clear',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementClearRequest',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_clear_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementClearResult',
        schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_clear_result$schema,
      },
      sourceLocation: {"file":"packages/prompt/prompt-enhancement/src/index.ts","line":145,"column":9},
    },
    {
      id: 'dsh-prompt-enhancement#promptEnhancement/delete',
      service: 'promptEnhancement',
      namespace: 'promptEnhancement',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementDeleteRequest',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementDeleteResult',
        schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_delete_result$schema,
      },
      sourceLocation: {"file":"packages/prompt/prompt-enhancement/src/index.ts","line":136,"column":9},
    },
    {
      id: 'dsh-prompt-enhancement#promptEnhancement/enhance',
      service: 'promptEnhancement',
      namespace: 'promptEnhancement',
      method: 'enhance',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementRequest',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementEnhanceResult',
        schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_result$schema,
      },
      sourceLocation: {"file":"packages/prompt/prompt-enhancement/src/index.ts","line":159,"column":9},
    },
    {
      id: 'dsh-prompt-enhancement#promptEnhancement/list',
      service: 'promptEnhancement',
      namespace: 'promptEnhancement',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementListRequest',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementListResult',
        schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_list_result$schema,
      },
      sourceLocation: {"file":"packages/prompt/prompt-enhancement/src/index.ts","line":123,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
