/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_clear_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly().optional(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_clear_result$schema = z.object({
  'deleted': z.number().readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_delete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_delete_result$schema = z.object({
  'deleted': z.boolean().readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_parameter_1$schema = z.object({
  'prompt': z.string().readonly(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_result$schema = z.object({
  'record': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly(),
  'originalPrompt': z.string().readonly(),
  'enhancedPrompt': z.string().readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly(),
  'trace': z.array(z.object({
  'kind': z.union([z.literal("context"), z.literal("model")]).readonly(),
  'label': z.string().readonly(),
  'reference': z.string().readonly().optional(),
  'summary': z.string().readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
}).readonly(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_list_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly().optional(),
})
const _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_list_result$schema = z.object({
  'records': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'mode': z.union([z.literal("prompt"), z.literal("project")]).readonly(),
  'originalPrompt': z.string().readonly(),
  'enhancedPrompt': z.string().readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly(),
  'trace': z.array(z.object({
  'kind': z.union([z.literal("context"), z.literal("model")]).readonly(),
  'label': z.string().readonly(),
  'reference': z.string().readonly().optional(),
  'summary': z.string().readonly().optional(),
  'status': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("completed")]).readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
})

export const TYPERT = {
  package: 'dsh-prompt-enhancement',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-prompt-enhancement#promptEnhancement/clear',
      service: 'promptEnhancement',
      namespace: 'promptEnhancement',
      method: 'clear',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementClearRequest',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_clear_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementClearResult',
        schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_clear_result$schema,
      },
      sourceLocation: {"file":"packages/prompt/prompt-enhancement/src/index.ts","line":145,"column":9},
    },
    {
      id: 'dsh-prompt-enhancement#promptEnhancement/delete',
      service: 'promptEnhancement',
      namespace: 'promptEnhancement',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementDeleteRequest',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementDeleteResult',
        schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_delete_result$schema,
      },
      sourceLocation: {"file":"packages/prompt/prompt-enhancement/src/index.ts","line":136,"column":9},
    },
    {
      id: 'dsh-prompt-enhancement#promptEnhancement/enhance',
      service: 'promptEnhancement',
      namespace: 'promptEnhancement',
      method: 'enhance',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementRequest',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementEnhanceResult',
        schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_enhance_result$schema,
      },
      sourceLocation: {"file":"packages/prompt/prompt-enhancement/src/index.ts","line":159,"column":9},
    },
    {
      id: 'dsh-prompt-enhancement#promptEnhancement/list',
      service: 'promptEnhancement',
      namespace: 'promptEnhancement',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementListRequest',
            schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-prompt-enhancement/client#PromptEnhancementListResult',
        schema: _deepseek_ai_dsh_prompt_enhancement_promptEnhancement_list_result$schema,
      },
      sourceLocation: {"file":"packages/prompt/prompt-enhancement/src/index.ts","line":123,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host prompt rewriting service with bounded read-only context and durable history.",
        "summary": "Host prompt rewriting service with bounded read-only context and durable history.",
        "tags": [],
        "jsDoc": "/** Host prompt rewriting service with bounded read-only context and durable history. */",
        "key": "promptEnhancement",
        "exportName": "PromptEnhancementService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(request: PromptEnhancementListRequest): PromptEnhancementListResult",
            "summary": "List immutable enhancement records matching the supplied filters.",
            "jsDoc": "/** List immutable enhancement records matching the supplied filters.\n * @param request - optional history filters.\n * @returns matching records.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') async delete(request: PromptEnhancementDeleteRequest): Promise<PromptEnhancementDeleteResult>",
            "summary": "Delete one immutable enhancement record.",
            "jsDoc": "/** Delete one immutable enhancement record.\n * @param request - record identity.\n * @returns deletion postcondition.\n */"
          },
          {
            "kind": "method",
            "name": "clear",
            "signature": "@Remote('clear') async clear(request: PromptEnhancementClearRequest): Promise<PromptEnhancementClearResult>",
            "summary": "Delete every record matching the supplied filters.",
            "jsDoc": "/** Delete every record matching the supplied filters.\n * @param request - optional filters.\n * @returns number of deleted records.\n */"
          },
          {
            "kind": "method",
            "name": "enhance",
            "signature": "@Remote('enhance') async enhance(agent: Agent, request: PromptEnhancementRequest, signal: AbortSignal): Promise<PromptEnhancementEnhanceResult>",
            "summary": "Generate one enhanced prompt without starting an Agent turn.",
            "jsDoc": "/** Generate one enhanced prompt without starting an Agent turn.\n * @param agent - Session-scoped Agent used for model and filesystem access.\n * @param request - draft and mode.\n * @param signal - cancellation signal.\n * @returns completed record.\n */"
          }
        ],
        "types": [
          {
            "name": "Agent",
            "declaration": "export interface Agent {\n    readonly id: SessionId;\n    readonly options: AgentOptions;\n    readonly session: Session;\n    readonly inbox: Inbox;\n    readonly status: AgentStatus;\n    readonly ctx: Context;\n    cancel(cause: AgentCancelCause, options?: CancelOptions): void;\n    whenIdle(): Promise<void>;\n    runMaintenance<T>(task: (signal: AbortSignal) => Promise<T>): Promise<T>;\n    send(message: UserMessage, target: InboxTarget, wakeup: boolean): void;\n    followup(message: UserMessage): void;\n    steer(message: UserMessage): void;\n    inject(message: UserMessage): void;\n}"
          },
          {
            "name": "AgentCancelCause",
            "declaration": "export type AgentCancelCause = { readonly kind: 'user'; } | { readonly kind: 'parent'; } | { readonly kind: 'hook'; readonly reason: string; } | { readonly kind: 'disposed'; };"
          },
          {
            "name": "AgentOptions",
            "declaration": "export interface AgentOptions {\n    provider?: string;\n    model?: string;\n    maxTokens?: number;\n}"
          },
          {
            "name": "AgentStatus",
            "declaration": "export type AgentStatus = 'idle' | 'running';"
          },
          {
            "name": "ApprovalOutcome",
            "declaration": "export type ApprovalOutcome = 'allowed-once' | 'rejected' | 'cancelled' | 'unavailable';"
          },
          {
            "name": "ApprovalPolicy",
            "declaration": "export type ApprovalPolicy = 'ask' | 'never';"
          },
          {
            "name": "ApprovalRequestId",
            "declaration": "export type ApprovalRequestId = Branded<'ApprovalRequestId'>;"
          },
          {
            "name": "AssistantMessage",
            "declaration": "export interface AssistantMessage extends Message {\n    readonly role: 'assistant';\n    readonly source: ModelMessageSource;\n}"
          },
          {
            "name": "AssistantProvenance",
            "declaration": "export interface AssistantProvenance {\n    provider: string;\n    model: string;\n    replayState?: unknown;\n}"
          },
          {
            "name": "AttachmentId",
            "declaration": "export type AttachmentId = Branded<'AttachmentId'>;"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "CallId",
            "declaration": "export type CallId = Branded<'CallId'>;"
          },
          {
            "name": "CancelOptions",
            "declaration": "export interface CancelOptions {\n    keepInbox?: boolean | undefined;\n}"
          },
          {
            "name": "CodeDispatchEventData",
            "declaration": "export interface CodeDispatchEventData extends CodeDispatchStartEventData {\n    isError: boolean;\n    content: ContentBlock[];\n}"
          },
          {
            "name": "CodeDispatchStartEventData",
            "declaration": "export interface CodeDispatchStartEventData {\n    rootCallId: CallId;\n    parentCallId: CallId;\n    subCallId: CallId;\n    name: string;\n    arguments: unknown;\n}"
          },
          {
            "name": "CommandId",
            "declaration": "export type CommandId = Branded<'CommandId'>;"
          },
          {
            "name": "CommandSource",
            "declaration": "export type CommandSource = CommandSourceMap[keyof CommandSourceMap];"
          },
          {
            "name": "CommandSourceMap",
            "declaration": "export interface CommandSourceMap {\n    user: { kind: 'user'; };\n}"
          },
          {
            "name": "ContentBlock",
            "declaration": "export type ContentBlock = ContentBlockMap[ContentBlockType];"
          },
          {
            "name": "ContentBlockMap",
            "declaration": "export interface ContentBlockMap {\n    text: TextBlock;\n    reasoning: ReasoningBlock;\n    image: ImageBlock;\n    'tool-call': ToolCallBlock;\n    'tool-result': ToolResultBlock;\n}"
          },
          {
            "name": "ContentBlockType",
            "declaration": "export type ContentBlockType = keyof ContentBlockMap;"
          },
          {
            "name": "ContextFormed",
            "declaration": "export type ContextFormed = { readonly form?: never; } | { readonly form: 'instructions'; } | { readonly form: 'catalog'; } | { readonly form: 'snapshot'; readonly sections: readonly ContextSnapshotSection[]; } | { readonly form: 'notice'; readonly summary: string; } | { readonly form: 'relay'; } | { readonly form: 'recall'; };"
          },
          {
            "name": "ContextSnapshotSection",
            "declaration": "export interface ContextSnapshotSection {\n    readonly name: string;\n    readonly text: string;\n}"
          },
          {
            "name": "EpochHeader",
            "declaration": "export interface EpochHeader {\n    config: LlmCallConfig;\n    adapterDefaults?: LlmCallConfigAdapterDefaults;\n    system?: string;\n    tools?: ToolSchema[];\n}"
          },
          {
            "name": "FinishReason",
            "declaration": "export type FinishReason = FinishReasonMap[keyof FinishReasonMap];"
          },
          {
            "name": "FinishReasonMap",
            "declaration": "export interface FinishReasonMap {\n    stop: { kind: 'stop'; };\n    'tool-calls': { kind: 'tool-calls'; };\n    'max-tokens': { kind: 'max-tokens'; };\n    aborted: { kind: 'aborted'; failure: LlmFailure; };\n    error: { kind: 'error'; failure: LlmFailure; };\n}"
          },
          {
            "name": "GoalBlockReason",
            "declaration": "export interface GoalBlockReason {\n    readonly code: string;\n    readonly message: string;\n}"
          },
          {
            "name": "GoalChangeMeta",
            "declaration": "export type GoalChangeMeta = GoalSnapshotChangeMeta | GoalClearChangeMeta;"
          },
          {
            "name": "GoalClearChangeMeta",
            "declaration": "export interface GoalClearChangeMeta {\n    readonly kind: 'goal/change';\n    readonly version: 1;\n    readonly operation: 'clear';\n    readonly cleared: GoalRef;\n    readonly clearedAt: number;\n}"
          },
          {
            "name": "GoalId",
            "declaration": "export type GoalId = Branded<'GoalId'>;"
          },
          {
            "name": "GoalMessageSource",
            "declaration": "export interface GoalMessageSource {\n    readonly kind: 'goal';\n    readonly goalId: GoalId;\n    readonly revision: number;\n    readonly round: number;\n}"
          },
          {
            "name": "GoalOperation",
            "declaration": "export type GoalOperation = 'create' | 'edit' | 'pause' | 'resume' | 'complete' | 'block' | 'clear';"
          },
          {
            "name": "GoalPhase",
            "declaration": "export type GoalPhase = 'active' | 'paused' | 'blocked' | 'complete';"
          },
          {
            "name": "GoalRef",
            "declaration": "export interface GoalRef {\n    readonly id: GoalId;\n    readonly revision: number;\n}"
          },
          {
            "name": "GoalSnapshot",
            "declaration": "export interface GoalSnapshot extends GoalRef {\n    readonly objective: string;\n    readonly phase: GoalPhase;\n    readonly blockedReason?: GoalBlockReason;\n    readonly maxGoalRounds: number;\n}"
          },
          {
            "name": "GoalSnapshotChangeMeta",
            "declaration": "export interface GoalSnapshotChangeMeta {\n    readonly kind: 'goal/change';\n    readonly version: 1;\n    readonly operation: Exclude<GoalOperation, 'clear'>;\n    readonly goal: GoalSnapshot;\n    readonly roundsStarted: number;\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "ImageAttachmentRef",
            "declaration": "export interface ImageAttachmentRef {\n    attachmentId: AttachmentId;\n    mediaType: ImageMediaType;\n    bytes: number;\n    width: number;\n    height: number;\n    name?: string;\n}"
          },
          {
            "name": "ImageBlock",
            "declaration": "export interface ImageBlock {\n    type: 'image';\n    attachment: ImageAttachmentRef;\n}"
          },
          {
            "name": "ImageMediaType",
            "declaration": "export type ImageMediaType = 'image/png' | 'image/jpeg' | 'image/webp' | 'image/gif';"
          },
          {
            "name": "Inbox",
            "declaration": "export class Inbox {\n    get nextTurn(): readonly UserMessage[];\n    get nextStep(): readonly UserMessage[];\n    get hasPending(): boolean;\n    clear(): void;\n    claim(target: InboxTarget, turn: number): UserMessage[];\n    append(target: InboxTarget, message: UserMessage): void;\n    prepend(target: InboxTarget, message: UserMessage): void;\n    replace(messageId: MessageId, newMessage: UserMessage): boolean;\n    remove(messageId: MessageId): boolean;\n    splice(target: InboxTarget, start: number, deleteCount: number, inserted: UserMessage[]): UserMessage[];\n}"
          },
          {
            "name": "InboxTarget",
            "declaration": "export type InboxTarget = 'next-turn' | 'next-step';"
          },
          {
            "name": "JsonValue",
            "declaration": "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue; };"
          },
          {
            "name": "LlmCallConfig",
            "declaration": "export interface LlmCallConfig {\n    provider: string;\n    model: string;\n    reasoningEffort?: ReasoningEffortId;\n    temperature?: number;\n    maxTokens?: number;\n    stop?: string[];\n}"
          },
          {
            "name": "LlmCallConfigAdapterDefaults",
            "declaration": "export interface LlmCallConfigAdapterDefaults {\n    reasoningEffort?: true;\n    maxTokens?: true;\n}"
          },
          {
            "name": "LlmFailure",
            "declaration": "export interface LlmFailure {\n    readonly message: string;\n    readonly code: string;\n    readonly status?: number;\n    readonly providerRetryAfterMs?: number;\n    readonly requestId?: ProviderRequestId;\n}"
          },
          {
            "name": "Message",
            "declaration": "export interface Message {\n    readonly id: MessageId;\n    readonly role: 'system' | 'user' | 'assistant';\n    readonly content: ContentBlock[];\n    readonly source: MessageSource;\n}"
          },
          {
            "name": "MessageId",
            "declaration": "export type MessageId = Branded<'MessageId'>;"
          },
          {
            "name": "MessageSource",
            "declaration": "export type MessageSource = MessageSourceMap[keyof MessageSourceMap];"
          },
          {
            "name": "MessageSourceMap",
            "declaration": "export interface MessageSourceMap {\n    user: { kind: 'user'; };\n    plugin: { kind: 'plugin'; plugin: string; } & ContextFormed;\n    model: ModelMessageSource;\n    tool: ToolMessageSource;\n    goal: GoalMessageSource;\n}"
          },
          {
            "name": "ModelMessageSource",
            "declaration": "export interface ModelMessageSource extends AssistantProvenance {\n    kind: 'model';\n}"
          },
          {
            "name": "PromptEnhancementClearRequest",
            "declaration": "export interface PromptEnhancementClearRequest extends PromptEnhancementListRequest {\n}"
          },
          {
            "name": "PromptEnhancementClearResult",
            "declaration": "export interface PromptEnhancementClearResult {\n    readonly deleted: number;\n}"
          },
          {
            "name": "PromptEnhancementDeleteRequest",
            "declaration": "export interface PromptEnhancementDeleteRequest {\n    readonly id: PromptEnhancementId;\n}"
          },
          {
            "name": "PromptEnhancementDeleteResult",
            "declaration": "export interface PromptEnhancementDeleteResult {\n    readonly deleted: boolean;\n}"
          },
          {
            "name": "PromptEnhancementEnhanceResult",
            "declaration": "export interface PromptEnhancementEnhanceResult {\n    readonly record: PromptEnhancementRecord;\n}"
          },
          {
            "name": "PromptEnhancementId",
            "declaration": "export type PromptEnhancementId = Branded<'PromptEnhancementId'>;"
          },
          {
            "name": "PromptEnhancementListRequest",
            "declaration": "export interface PromptEnhancementListRequest {\n    readonly sessionId?: SessionId;\n    readonly workspaceId?: WorkspaceId;\n    readonly mode?: PromptEnhancementMode;\n    readonly status?: PromptEnhancementStatus;\n}"
          },
          {
            "name": "PromptEnhancementListResult",
            "declaration": "export interface PromptEnhancementListResult {\n    readonly records: readonly PromptEnhancementRecord[];\n}"
          },
          {
            "name": "PromptEnhancementMode",
            "declaration": "export type PromptEnhancementMode = 'prompt' | 'project';"
          },
          {
            "name": "PromptEnhancementRecord",
            "declaration": "export interface PromptEnhancementRecord {\n    readonly id: PromptEnhancementId;\n    readonly sessionId?: SessionId;\n    readonly workspaceId?: WorkspaceId;\n    readonly mode: PromptEnhancementMode;\n    readonly originalPrompt: string;\n    readonly enhancedPrompt?: string;\n    readonly status: PromptEnhancementStatus;\n    readonly trace: readonly PromptEnhancementTraceStep[];\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "PromptEnhancementRequest",
            "declaration": "export interface PromptEnhancementRequest {\n    readonly prompt: string;\n    readonly mode: PromptEnhancementMode;\n}"
          },
          {
            "name": "PromptEnhancementStatus",
            "declaration": "export type PromptEnhancementStatus = 'completed' | 'failed' | 'cancelled';"
          },
          {
            "name": "PromptEnhancementTraceStep",
            "declaration": "export interface PromptEnhancementTraceStep {\n    readonly kind: 'context' | 'model';\n    readonly label: string;\n    readonly reference?: string;\n    readonly summary?: string;\n    readonly status: 'completed' | 'failed' | 'cancelled';\n}"
          },
          {
            "name": "ProviderRequestId",
            "declaration": "export type ProviderRequestId = Branded<'ProviderRequestId'>;"
          },
          {
            "name": "ReasoningBlock",
            "declaration": "export interface ReasoningBlock {\n    type: 'reasoning';\n    text: string;\n}"
          },
          {
            "name": "ReasoningEffortId",
            "declaration": "export type ReasoningEffortId = Branded<'ReasoningEffortId'>;"
          },
          {
            "name": "ReplayEnvelope",
            "declaration": "export interface ReplayEnvelope {\n    response: unknown;\n    blocks?: readonly unknown[];\n}"
          },
          {
            "name": "RequestContext",
            "declaration": "export interface RequestContext {\n    provider: string;\n    model: string;\n    contextWindow?: number;\n}"
          },
          {
            "name": "RequestHeaderReason",
            "declaration": "export type RequestHeaderReason = 'initial' | 'resume' | 'change';"
          },
          {
            "name": "Session",
            "declaration": "export class Session {\n    get surface(): SessionSurface;\n    readonly header: SessionHeader;\n    get id(): SessionId;\n    readonly firstLiveSeq: number;\n    get events(): readonly SessionEvent[];\n    get seq(): number;\n    append<T extends SessionEventType>(type: T, data: SessionEventMap[T], ...opts: T extends SurfaceEventType ? [opts: SurfaceIntent] : []): SessionEvent<T>;\n    requestHeader(): EpochHeader | undefined;\n    requestContext(): RequestContext | undefined;\n    deriveMessages(): Message[];\n    deriveEventMessage(event: SessionEvent): Message | null;\n}"
          },
          {
            "name": "SessionEvent",
            "declaration": "export type SessionEvent<T extends SessionEventType = SessionEventType> = { [K in SessionEventType]: { type: K; seq: number; time: number; data: SessionEventMap[K]; ignorable?: true; } & (K extends SurfaceEventType ? { sourceEventSeqs?: number[]; surfaceOp?: SurfaceOp; } : object) }[T];"
          },
          {
            "name": "SessionEventMap",
            "declaration": "export interface SessionEventMap {\n    'turn/start': { turn: number; };\n    'turn/end': { turn: number; reason: TurnEndReason; };\n    'step/start': { turn: number; step: number; };\n    'step/end': { turn: number; step: number; };\n    'user/message': UserMessage;\n    'assistant/chunk': { turn: number; step: number; chunk: StreamChunk; };\n    'assistant/message': { turn: number; step: number; message: AssistantMessage; usage?: TokenUsage; };\n    'tool/call': { turn: number; step: number; callId: CallId; name: string; arguments: string; };\n    'tool/result': { turn: number; step: number; message: ToolResultMessage; error?: { name: string; code: string; }; meta?: JsonValue; };\n    'todo/write': { todos: TodoItem[]; };\n    'request/header': { header: EpochHeader; reason: RequestHeaderReason; };\n    'request/context': RequestContext;\n    'session/end-seed': Record<string, never>;\n    'agent/inbox/spliced': { target: InboxTarget; start: number; removedCount?: number; inserted: UserMessage[]; outcome?: 'canceled'; };\n    'command/run': { commandId: CommandId; name: string; args?: string; source: CommandSource; };\n    'command/done': { commandId: CommandId; kind: 'success' | 'error'; text?: string; sourceEventSeq?: number; };\n    'approval/asked': { id: ApprovalRequestId; toolName: string; callId?: CallId; reason?: string; };\n    'approval/decided': { id: ApprovalRequestId; outcome: ApprovalOutcome; };\n    'approval/policy': { policy: ApprovalPolicy; source?: 'delegation'; };\n    'tool/code-dispatch-start': CodeDispatchStartEventData;\n    'tool/code-dispatch': CodeDispatchEventData;\n    'goal/change': GoalChangeMeta;\n}"
          },
          {
            "name": "SessionEventType",
            "declaration": "export type SessionEventType = keyof SessionEventMap;"
          },
          {
            "name": "SessionHeader",
            "declaration": "export interface SessionHeader {\n    readonly version: number;\n    readonly id: SessionId;\n    readonly createdAt: number;\n    readonly cwd?: string;\n    readonly parentSession?: SessionId;\n    readonly seedLength?: number;\n    readonly origin?: 'subagent';\n    readonly delegationDepth?: number;\n    readonly agentPreset?: string;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "SessionSurface",
            "declaration": "export interface SessionSurface {\n    readonly nodes: readonly number[];\n    readonly replaceGeneration: number;\n}"
          },
          {
            "name": "StreamChunk",
            "declaration": "export type StreamChunk = { type: 'block-start'; index: number; blockType: ContentBlockType; } | { type: 'text-delta'; index: number; text: string; } | { type: 'reasoning-delta'; index: number; text: string; } | { type: 'tool-call-delta'; index: number; id: CallId; name?: string; argumentsDelta: string; } | { type: 'block-end'; index: number; block: ContentBlock; } | { type: 'usage'; usage: TokenUsage; } | { type: 'finish'; reason: FinishReason; replayState?: ReplayEnvelope; };"
          },
          {
            "name": "SurfaceEventType",
            "declaration": "export type SurfaceEventType = 'user/message' | 'assistant/message' | 'tool/result';"
          },
          {
            "name": "SurfaceIntent",
            "declaration": "export interface SurfaceIntent {\n    surfaceOp: SurfaceOp;\n    sourceEventSeqs?: number[];\n}"
          },
          {
            "name": "SurfaceOp",
            "declaration": "export type SurfaceOp = 'append' | { op: 'replace'; start: number; end: number; };"
          },
          {
            "name": "TextBlock",
            "declaration": "export interface TextBlock {\n    type: 'text';\n    text: string;\n}"
          },
          {
            "name": "TodoItem",
            "declaration": "export interface TodoItem {\n    content: string;\n    status: 'pending' | 'in_progress' | 'completed';\n}"
          },
          {
            "name": "TokenUsage",
            "declaration": "export interface TokenUsage {\n    inputTokens: number;\n    outputTokens: number;\n    cacheReadTokens?: number;\n    cacheWriteTokens?: number;\n    reasoningTokens?: number;\n}"
          },
          {
            "name": "ToolCallBlock",
            "declaration": "export interface ToolCallBlock {\n    type: 'tool-call';\n    id: CallId;\n    name: string;\n    arguments: string;\n}"
          },
          {
            "name": "ToolMessageSource",
            "declaration": "export interface ToolMessageSource {\n    kind: 'tool';\n    callId: CallId;\n}"
          },
          {
            "name": "ToolResultBlock",
            "declaration": "export interface ToolResultBlock {\n    type: 'tool-result';\n    toolCallId: CallId;\n    content: ContentBlock[];\n    isError?: boolean;\n}"
          },
          {
            "name": "ToolResultMessage",
            "declaration": "export interface ToolResultMessage extends Message {\n    readonly role: 'user';\n    readonly content: [ToolResultBlock];\n    readonly source: ToolMessageSource;\n}"
          },
          {
            "name": "ToolSchema",
            "declaration": "export interface ToolSchema {\n    name: string;\n    description: string;\n    parameters: Record<string, unknown>;\n}"
          },
          {
            "name": "TurnEndCancelCause",
            "declaration": "export type TurnEndCancelCause = AgentCancelCause | { readonly kind: 'legacy'; };"
          },
          {
            "name": "TurnEndReason",
            "declaration": "export type TurnEndReason = TurnEndReasonMap[keyof TurnEndReasonMap];"
          },
          {
            "name": "TurnEndReasonMap",
            "declaration": "export interface TurnEndReasonMap {\n    completed: { kind: 'completed'; };\n    aborted: { kind: 'aborted'; reason: TurnEndCancelCause; };\n    blocked: { kind: 'blocked'; };\n    error: { kind: 'error'; error: LlmFailure; };\n    'max-tokens': { kind: 'max-tokens'; };\n    interrupted: { kind: 'interrupted'; };\n}"
          },
          {
            "name": "UserMessage",
            "declaration": "export interface UserMessage extends Message {\n    readonly role: 'user';\n}"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = WorkspaceIdBrand;"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
